# Generated by Django 4.1.5 on 2023-03-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
