# Generated by Django 4.1.5 on 2023-03-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_of_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
