# Generated by Django 4.1.5 on 2023-03-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_birth_date_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
